### ISSUE TITLE
estouchy on Matrix

### ISSUE THREAD

**Issue by scherom** [adarmalik/service.rotdev#2]
Hi wanting to do  a similar project like you, givin live back to an old radio with kodi and rotary encoder, 
However, I do not have any programming skills, so I thought your solution was just simple and right for me.

I tried to install your addon and got an error
could not resolve "xbmc.python" version="2.14.0"

I tried to install it on Raspberry Pi 3B+, Libreelec 10.0.1 (Kodi 19.3 - Matrix) , Skin Estouchy
I could not find any python reference and as Kodi has moved to Python 3... 
https://kodi.wiki/view/Migration_to_Python_3 (though as I said I am not technically skilled and not sure what that means).
Is there an easy way to update that?
I hope you might have some time to look into this. Thank you very much!!

**Comment by adarmalik** [comment]
Hi @scherom,
great to hear that someone finds my scribbles here useful :)
Unfortunately I don't have a setup now to test any migration.
Can you try if simply change the require in addon.xml is sufficient?
Just change the 2.14.0 to 3.0.0 in the line
`<import addon="xbmc.python" version="2.14.0" />`

Can you test and report back if it works?

**Comment by scherom** [comment]
Hi Thank you, great to read the.
I wil see if that works, tomorrow. I was just wondering if as per the link I posted calling any "import addon" was necessairy? Does the commands in the script also works the same under 3.0 or 2.14 or would python itself require any change?

**Comment by adarmalik** [comment]
Yes, the import is required.

**Comment by scherom** [comment]
Hi I did change the entry reg xbmc.python

It imported the addon (showed the duck), but then referred to the log for errors
I guess that is the part that was called after importing the addon... 
Can you help me with that?


2022-01-27 08:45:49.806 T:1434     INFO <general>: CAddonMgr::FindAddon: service.rotdev v1.0.0 installed
2022-01-27 08:45:49.882 T:1438     INFO <general>: initializing python engine.
2022-01-27 08:45:50.650 T:1438    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: module 'xbmc' has no attribute 'LOGNOTICE'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/service.rotdev/resources/lib/service.py", line 91, in <module>
                                                       rot.setup()
                                                     File "/storage/.kodi/addons/service.rotdev/resources/lib/service.py", line 46, in setup
                                                       log("setup")
                                                     File "/storage/.kodi/addons/service.rotdev/resources/lib/service.py", line 13, in log
                                                       xbmc.log(msg=message, level=xbmc.LOGNOTICE)
                                                   AttributeError: module 'xbmc' has no attribute 'LOGNOTICE'
                                                   -->End of Python script error report<--

**Comment by adarmalik** [comment]
Thanks for testing it.
This should be easy to fix. The log interface has changed slightly.
I will try to do that tonight.

If you feel brave you can simply replace each LOGNOTICE occurance in that file by LOGINFO. Maybe that does the trick already :)

**Comment by scherom** [comment]
Great thank you for your reply... I will try that. and let you know

**Comment by scherom** [comment]
OK Chaniing LOGNOTICE to LOGINFO did eliminate the error message regarding the logs.
but new appear
Python interpreter stopped
2022-01-27 14:07:38.407 T:1017     INFO <general>: Loading skin file: CustomVolume.xml, load type: KEEP_IN_MEMORY
2022-01-27 14:07:43.430 T:1068    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'dict' object has no attribute 'has_key'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/service.rotdev/resources/lib/service.py", line 94, in <module>
                                                       rot.read()
                                                     File "/storage/.kodi/addons/service.rotdev/resources/lib/service.py", line 75, in read
                                                       self.__rotate(tmp[4])
                                                     File "/storage/.kodi/addons/service.rotdev/resources/lib/service.py", line 39, in __rotate
                                                       vol = getVolume()
                                                     File "/storage/.kodi/addons/service.rotdev/resources/lib/service.py", line 19, in getVolume
                                                       if (dct.has_key("result")) and (dct["result"].has_key("volume")):
                                                   AttributeError: 'dict' object has no attribute 'has_key'
                                                   -->End of Python script error report<--

2022-01-27 14:07:44.050 T:1068     INFO <general>: Python interpreter stopped

I hope that can be easy too...

**Comment by adarmalik** [comment]
Darn, :)

you could try to replace that line with

`if ("result" in dct and  "volume" in dct["result"]):`

**Comment by scherom** [comment]
Hi I hope I understood correctly.
I changed the line 19 to the following

if ("result" in dct and "volume" in dct["result"]):
    curVol = dct["result"]["volume"]
    return curVol

It sais that here is nevertheless an error


2022-01-27 16:39:49.560 T:1063     INFO <general>: CAddonMgr::FindAddon: service.rotdev v1.0.0 installed
2022-01-27 16:39:49.583 T:1214     INFO <general>: initializing python engine.
2022-01-27 16:39:50.357 T:1214    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'SyntaxError'>
                                                   Error Contents: 'return' outside function (service.py, line 21)
                                                     File "/storage/.kodi/addons/service.rotdev/resources/lib/service.py", line 21
                                                       return curVol
                                                       ^
                                                   SyntaxError: 'return' outside function
                                                   -->End of Python script error report<--

2022-01-27 16:39:50.833 T:1214     INFO <general>: Python interpreter stopped

**Comment by adarmalik** [comment]
Probably you messed up indentation :)
I have created a branch and blindly tried a port. Can you check if it works for you?

**Comment by scherom** [comment]
Hi Thank you!
It installed fine.
And I think the only reference to it I find in the log is the following:
However, when I play musik moving the rotary encoder does not change anything...

2022-01-27 20:24:03.786 T:1071     INFO <general>: service.rotdev: b'setup'
2022-01-27 20:24:03.786 T:1071     INFO <general>: service.rotdev: b'stop'
2022-01-27 20:24:03.849 T:1071     INFO <general>: service.rotdev: b'config: /dev/input/event4 5'

I did use Pin# 23 and 24 as per your description to connect the left and right pins from the rotary endocder and the middel on connected to ground on pin 14. (correct to read pins not as GPIO 23 or GPIO 24, as I do sometimes mix that up?)

I found to config.txt 
/flash/config.txt  -> I add the lines as discribed 
/usr/share/bootloader/config.txt -> this I could not find a way to add them...

Thank you again somuch for the help

**Comment by adarmalik** [comment]
For the wiring you could check here: https://www.acmesystems.it/rotary_encoder
The config.txt can be found in /boot/config.txt of your running Raspberry Pi system.

**Comment by scherom** [comment]
Thank you I will try tomorrow or over the week-end to sort that out. I keep you posted

**Comment by scherom** [comment]
Exellent it works!

Additionally, what I needed to figure out
* on libreelec the config.txt is in /flash
* as I used a STEC11B03 Encoder - that is not labled the same way as the KY40 but the link (first in your readme) explained A=CLK, B=DT
* the PIN are actually not the physical pins but the GPIO numbers so pin_a=23 = GPIO23 = physical pin 16 (RaspPi 3B+)

One issue how-ever ... it looks like the zero level is reached already when Kodi displays +/-30% ... and I am not sure volume goes up again to full volume 100% ... (Any idea to test that?)

Thinking forward (thinking of xmas)...
Can one configure the pins in the add-on configuration
Can one make one module allowing 3 of such rotary encoder with pushbutton
1) = volume -> rotation volume+ & volume /  push=mute/unmute
2) = move curser left right / push = enter (long enter = contect menue)
3) =move curser up down / push = enter (long enter = context menue)
(with pins again defined in the configuration, to allow not using anyone used allready)
or create a flexible command assignment of the commands

Like this addon in volumio
(https://user-images.githubusercontent.com/19372245/151534275-3bc58373-393d-46ee-a7ae-d311c2ad9c53.png)](https://volumio.github.io/docs/Plugins_User_Manuals/rotaryencoder2/Rotary_Encoder_II.html)

Somuch if you are still looking for a project...

**Comment by adarmalik** [comment]
:D great to hear that it works for you now. Maybe you can post some pictures of your setup somewhere, so others get inspired too.

Your proposal is to have three different rotary encoders or one with three functions?
I think with the three different encoders that shouldn't be a big of a deal.

**Comment by scherom** [comment]
great idea will make some pictures.
I thought of 3 rotary encoder performing these tasks..

**Comment by scherom** [comment]
Thank you so much... here some pictures of my project.
Refitting a childhood radio of my partner.
I changed the tape-deck with a 5" touch display. All the buttons are just dummies, for the time beeing, except for the first rotary button that I could turn into a volume control thanks to your help!

![IMG_3712](https://user-images.githubusercontent.com/19372245/151595971-399e65b0-47d1-4328-8a2f-7e056d43620b.jpeg)
![IMG_3709](https://user-images.githubusercontent.com/19372245/151595994-f886a51f-8ca6-425d-9b73-375a5df81848.jpeg)
![IMG_3708](https://user-images.githubusercontent.com/19372245/151596027-8b98e5e8-7241-45e4-ac78-b842c222694f.jpeg)
![IMG_3714](https://user-images.githubusercontent.com/19372245/151596072-a357fbe2-1168-43fa-8c12-ca2ed83e20a6.jpeg)

**Comment by adarmalik** [comment]
:D I thought you do some blog post or so.
Nice an RFT Stern Recorder.

**Comment by scherom** [comment]
Thank you, yes it's a nice radio! And very well fitted for this.. the tabe deck hat the (almost, by 1 mm) perfect size for the 5" display. 
Do you know a forum, where I can post that? I don't have a blog.
